#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
polybar bspwm --config=~/.config/polybar/config.ini &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config normal_border_color "#000000"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

bspc config border_width         3
bspc config window_gap          20
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding            -7

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

